name: Snapshot pre-release

on:
    push:
        branches: [main]

jobs:
    snapshot:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  registry-url: "https://registry.npmjs.org/"

            - name: Install
              run: bun install --frozen-lockfile

            - name: Build
              run: bun run prepublish
              working-directory: packages/core

            - name: Version snapshot (unique per commit)
              run: changeset version --snapshot canary-$(git rev-parse --short HEAD)

            - name: Publish snapshot under tag=canary
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: changeset publish --tag canary --no-git-tag
