name: Prerelease

on:
    push:
        branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    prerelease:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Install
              run: bun install --frozen-lockfile

            - name: Check for changesets
              id: changesets
              run: |
                if ls .changeset/*.md 2>/dev/null | grep -v README > /dev/null; then
                  echo "hasChangesets=true" >> $GITHUB_OUTPUT
                else
                  echo "hasChangesets=false" >> $GITHUB_OUTPUT
                fi

            - name: Version and publish snapshot
              if: steps.changesets.outputs.hasChangesets == 'true'
              run: |
                bun changeset version --snapshot canary-$(git rev-parse --short HEAD)
                cd packages/core && bun publish --tag canary
              env:
                  NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
