name: Release package

on:
    push:
        branches: [main]

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  registry-url: "https://registry.npmjs.org/"

            - name: Install
              run: bun install --frozen-lockfile

            - name: Typecheck
              run: bun run typecheck

            - name: Lint
              run: bun run lint

            - name: Build
              run: bun run prepublish
              working-directory: packages/core

            - name: Create Release PR or Publish
              uses: changesets/action@v1
              with:
                  version: changeset version
                  publish: changeset publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
