name: Release

on:
    push:
        branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1

            - name: Install
              run: bun install --frozen-lockfile

            - name: Typecheck
              run: bun run typecheck

            - name: Lint
              run: bun run lint

            - name: Test
              run: bun run test

            - name: Create Release Pull Request or Version & Publish
              id: changesets
              uses: changesets/action@v1
              with:
                  version: bun changeset version
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish with bun
              if: steps.changesets.outputs.hasChangesets == 'false'
              run: |
                  bun run changeset tag
                  cd packages/core && bun publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
